# -*- mode: ruby -*-
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "https://vagrantcloud.com/ubuntu/boxes/trusty64"
  config.vm.hostname = "dev1.wangjia.com"
  config.vm.network "private_network", ip: "192.168.99.111"
  config.vm.provision "shell", path: "../shell_scripts/setup_erlang_dev.sh", :privileged => false
  config.vm.provision "shell", path: "../shell_scripts/setup_erlang_dev_hosts.sh", :privileged => false

  config.ssh.forward_agent = true
  config.vm.synced_folder "~/Share", "/home/vagrant/Share"

  ## set Memory size
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end
end
