# -*- mode: ruby -*-
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "https://vagrantcloud.com/ubuntu/boxes/trusty64"
  config.vm.network "private_network", ip: "192.168.88.101"
  config.vm.provision "shell", path: "../shell_scripts/setup_ubuntu_dev_tools.sh", :privileged => false
  config.vm.synced_folder "~/Share", "/home/vagrant/Share"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
  end
end
